steps:


- name: docker-maven
  dir: 'app/'
  args: ['build' , '-t' , 'lingisi/maven:latest' , '.']
  args: ['push' , '-t' , 'lingisi/maven:latest' ]



- name: docker-node
  dir: 'app/'
  args: ['build' , '-t' , 'lingisi/backend-node:latest' , '.']
  args: ['push' , '-t' , 'lingisi/backend-node:latest' ]

