steps:


- name: node
  dir: app
  args: ['build' , '.']

- name: node
  dir: app
  entrypoint: npm
  args: ['install']

- name: node
  dir: app
  entrypoint: npm
  args: ['test']


- name: maven
  entrypoint: mvn
  args: ['test']
- name: maven 
  entrypoint: mvn
  args: ['build' , '.']




- name: docker-maven
  dir: 'app/'
  args: ['build' , '-t' , 'lingisi/maven:latest' , '.']
  args: ['push' , '-t' , 'lingisi/maven:latest' ]



- name: docker-node
  dir: 'app/'
  args: ['build' , '-t' , 'lingisi/backend-node:latest' , '.']
  args: ['push' , '-t' , 'lingisi/backend-node:latest' ]

